from __future__ import annotations

import io
import zipfile
from xml.sax.saxutils import escape

from .checksum import fingerprint, checksum_from_manifest
from .types import IntentManifest

NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"


def _para(text: str, bold: bool = False, size: int = 22) -> str:
    run_props = f'<w:rPr><w:sz w:val="{size}"/><w:szCs w:val="{size}"/>'
    if bold:
        run_props += "<w:b/>"
    run_props += "</w:rPr>"
    return (
        f'<w:p><w:r>{run_props}<w:t xml:space="preserve">{escape(text)}</w:t></w:r></w:p>'
    )


def _docx(body_xml: str) -> bytes:
    document = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="{NS}">
  <w:body>
    {body_xml}
    <w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1080" w:right="1080" w:bottom="1080" w:left="1080"/></w:sectPr>
  </w:body>
</w:document>'''
    types = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>"""
    rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>"""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", types)
        zf.writestr("_rels/.rels", rels)
        zf.writestr("word/document.xml", document)
        zf.writestr(
            "word/_rels/document.xml.rels",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>""",
        )
    return buf.getvalue()


def agreement_template() -> bytes:
    tags = [
        ("{{title}}", True, 36),
        ("Customer: {{customer}}", False, 22),
        ("Vendor: {{vendor}}", False, 22),
        ("1.1 Contract Value. The total contract value is {{contract_value}}.", False, 22),
        ("1.2 Term. This Agreement shall remain in force for {{term_months}} months.", False, 22),
        ("1.3 Payment. Invoices are payable within {{payment_terms_days}} days.", False, 22),
        ("2.1 Either party may terminate this Agreement by providing {{termination_notice_days}} days written notice.", False, 22),
        ("2.2 {{renewal_clause}}", False, 22),
        ("3.1 Governing Law. This Agreement is governed by the laws of {{governing_law}}.", False, 22),
        ("3.2 Liability. {{guarantee_clause}}", False, 22),
        ("3.3 Exclusivity. {{exclusivity_clause}}", False, 22),
        ("Account name: {{account_name}}", False, 22),
        ("Bank: {{bank_name}}", False, 22),
        ("Account number: {{bank_account}}", False, 22),
        ("{{sow_block}}", False, 22),
        ("Signed by: {{signer_name}}", False, 22),
        ("{{fields_block}}", False, 16),
    ]
    return _docx("".join(_para(text, bold, size) for text, bold, size in tags))


def cover_sheet_template() -> bytes:
    tags = [
        ("SIGNGATE VERIFICATION CERTIFICATE", True, 36),
        ("Gate status: {{gate_status}}", True, 28),
        ("The final PDF matches the approved Intent Manifest.", False, 22),
        ("Intent Manifest hash: {{manifest_hash}}", False, 20),
        ("Verified at: {{verified_at}}", False, 20),
        ("1. Contract value: {{contract_value}}", False, 22),
        ("2. Term: {{term_label}}", False, 22),
        ("3. Termination notice: {{termination_label}}", False, 22),
        ("4. Automatic renewal: {{renewal_label}}", False, 22),
        ("5. Required attachment: {{sow_label}}", False, 22),
        ("Customer: {{customer}}    Vendor: {{vendor}}", False, 20),
        ("This cover sheet is generated by SignGate and merged in front of the instrument before eSign.", False, 18),
    ]
    return _docx("".join(_para(text, bold, size) for text, bold, size in tags))


def agreement_values(manifest: IntentManifest) -> dict[str, str]:
    value = manifest["commercial_terms"]["contract_value"]
    money = f"{value['currency']} {value['amount']:,}"
    sow = "Statement of Work" in manifest["required_attachments"]
    renewal = (
        f"This Agreement automatically renews for successive {manifest['commercial_terms']['term_months']}-month periods unless either party provides {manifest['legal_terms']['termination_notice_days']} days written notice."
        if manifest["legal_terms"]["auto_renewal"]
        else "This Agreement does not automatically renew. Any extension requires a new written instrument signed by both parties."
    )
    guarantee = (
        "The undersigned individual personally guarantees the Customer's obligations under this Agreement."
        if manifest["legal_terms"]["personal_guarantee"]
        else "Neither party provides a personal guarantee. No personal liability is assumed by any director, officer, or employee."
    )
    exclusive = (
        "Customer hereby appoints Vendor as its exclusive provider of the Services."
        if manifest["legal_terms"]["exclusivity"]
        else "This Agreement does not grant exclusivity. Customer may obtain similar services from other vendors."
    )
    fields = "\n".join(
        [
            "--- SIGNGATE INTENT FIELDS ---",
            f"document_type: {manifest['document_type']}",
            f"customer: {manifest['parties']['customer']}",
            f"vendor: {manifest['parties']['vendor']}",
            f"contract_value_amount: {value['amount']}",
            f"contract_value_currency: {value['currency']}",
            f"term_months: {manifest['commercial_terms']['term_months']}",
            f"payment_terms_days: {manifest['commercial_terms']['payment_terms_days']}",
            f"termination_notice_days: {manifest['legal_terms']['termination_notice_days']}",
            f"auto_renewal: {str(manifest['legal_terms']['auto_renewal']).lower()}",
            f"personal_guarantee: {str(manifest['legal_terms']['personal_guarantee']).lower()}",
            f"exclusivity: {str(manifest['legal_terms']['exclusivity']).lower()}",
            f"governing_law: {manifest['legal_terms']['governing_law']}",
            f"attachments: {', '.join(manifest['required_attachments'])}",
            f"bank_account: {manifest['bank_details']['account_number'] or ''}",
            f"bank_account_name: {manifest['bank_details']['account_name'] or ''}",
            f"bank_name: {manifest['bank_details']['bank_name'] or ''}",
            "--- END SIGNGATE INTENT FIELDS ---",
        ]
    )
    return {
        "title": manifest["title"].upper(),
        "customer": manifest["parties"]["customer"],
        "vendor": manifest["parties"]["vendor"],
        "contract_value": money,
        "term_months": str(manifest["commercial_terms"]["term_months"]),
        "payment_terms_days": str(manifest["commercial_terms"]["payment_terms_days"]),
        "termination_notice_days": str(manifest["legal_terms"]["termination_notice_days"]),
        "renewal_clause": renewal,
        "governing_law": manifest["legal_terms"]["governing_law"],
        "guarantee_clause": guarantee,
        "exclusivity_clause": exclusive,
        "account_name": manifest["bank_details"]["account_name"] or "—",
        "bank_name": manifest["bank_details"]["bank_name"] or "—",
        "bank_account": manifest["bank_details"]["account_number"] or "—",
        "sow_block": (
            "Schedule A — Statement of Work. This Statement of Work is attached to and forms part of the Agreement."
            if sow
            else ""
        ),
        "signer_name": manifest["signer"]["name"],
        "fields_block": fields,
    }


def cover_sheet_values(manifest: IntentManifest, verified_at: str) -> dict[str, str]:
    value = manifest["commercial_terms"]["contract_value"]
    sow = "Statement of Work" in manifest["required_attachments"]
    return {
        "gate_status": "OPEN",
        "manifest_hash": fingerprint(checksum_from_manifest(manifest)),
        "verified_at": verified_at,
        "contract_value": f"{value['currency']} {value['amount']:,}",
        "term_label": f"{manifest['commercial_terms']['term_months']} months",
        "termination_label": f"{manifest['legal_terms']['termination_notice_days']}-day termination",
        "renewal_label": "No automatic renewal" if not manifest["legal_terms"]["auto_renewal"] else "Automatic renewal",
        "sow_label": "Statement of Work required" if sow else "No Statement of Work",
        "customer": manifest["parties"]["customer"],
        "vendor": manifest["parties"]["vendor"],
    }
