[theme]
base = "light"
primaryColor = "#1b1a16"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#1b1a16"
font = "serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false
